import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Headers from '../components/layout/header/index';
import Footer from '../components/layout/footer/index';
import Providers from '../components/redux/providers'
import ThemeProvider from '../components/theme/index'



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
        <Providers>
          <Headers/>  
          <ThemeProvider>
          {children}
          </ThemeProvider>
          </Providers>
        <Footer/>
      </body>
    </html>
  );
}
